# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('firm_name', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('user_type', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
