# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
