# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_auto_20170220_1457'),
        ('user_details', '0002_auto_20170220_1113'),
    ]

    operations = [
    ]
