# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_auto_20170220_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='id',
        ),
        migrations.AddField(
            model_name='user_data',
            name='user_id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
