# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_auto_20170222_1318'),
        ('user_details', '0003_merge_20170220_1532'),
    ]

    operations = [
    ]
