# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=120)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
