# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=200)),
                ('amount', models.FloatField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Expense_Table',
        ),
    ]
