# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0002_auto_20170221_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense_data',
            old_name='Description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='expense_data',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense_data',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
