# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0005_auto_20170225_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_data',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense_data',
            name='modified',
            field=models.DateField(auto_now_add=True),
        ),
    ]
