# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('tax_id', models.IntegerField()),
                ('item_id', models.IntegerField(null=True)),
                ('created', models.DateField()),
                ('modified', models.DateField()),
            ],
        ),
    ]
