# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('created', models.IntegerField()),
                ('modified', models.IntegerField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total_tax', models.FloatField()),
                ('tax', models.FloatField()),
            ],
        ),
    ]
