# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_item', '0002_auto_20170222_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
