# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.IntegerField(),
        ),
    ]
