# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20170228_0654'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_data_purchase',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, max_length=120, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=120, null=True)),
                ('sub_total', models.FloatField(max_length=120)),
                ('tax_total', models.FloatField(max_length=120)),
                ('grand_total', models.FloatField(max_length=120)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('payment_status', models.BooleanField()),
                ('payment_mode', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='order_data_selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=120, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('order_type', models.CharField(blank=True, choices=[('Purchase', 'Purchase'), ('Sell', 'Sell')], max_length=120, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=120, null=True)),
                ('sub_total', models.FloatField(max_length=120)),
                ('tax_total', models.FloatField(max_length=120)),
                ('grand_total', models.FloatField(max_length=120)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('payment_status', models.BooleanField()),
                ('payment_mode', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now_add=True)),
                ('price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('total_tax', models.FloatField(null=True)),
                ('tax', models.FloatField(null=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item_data')),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
