# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20170228_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_data_purchase',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order_data_purchase',
            name='date_modified',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order_data_selling',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order_data_selling',
            name='date_modified',
            field=models.DateField(auto_now_add=True),
        ),
    ]
