# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20170220_0936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='order_data',
        ),
    ]
