# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20170220_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_data',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='order_data',
            name='customer_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order_data',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Purchase', 'Purchase'), ('Sell', 'Sell')], max_length=120, null=True),
        ),
    ]
