# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20170220_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_data',
            name='customer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
