# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20170228_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_data_purchase',
            name='grand_total',
            field=models.FloatField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order_data_selling',
            name='grand_total',
            field=models.FloatField(max_length=120, null=True),
        ),
    ]
