# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_data_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_data_selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, default=True, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=120, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('order_type', models.CharField(blank=True, choices=[('Purchase', 'Purchase'), ('Sell', 'Sell')], max_length=120, null=True)),
                ('tax', models.CharField(blank=True, max_length=120, null=True)),
                ('sub_total', models.FloatField(max_length=120)),
                ('tax_total', models.FloatField(max_length=120)),
                ('grand_total', models.FloatField(max_length=120)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('payment_status', models.BooleanField()),
                ('payment_mode', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_description', models.TextField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='order_data',
            new_name='order_data_purchase',
        ),
    ]
