# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20170228_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_data_purchase',
            name='order_id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
